name: sisyphus
version: 1.0.0
config-version: 2
profile: sisyphus
model-paths: ["dbt/models"]
test-paths: ["dbt/tests"]
clean-targets: ["target", "logs"]
models:
  sisyphus:
    staging:
      +materialized: view
    marts:
      +materialized: table
